/* ============================================================
   FRASES (leitura)  —  frases.jsx  →  window.Frases
   Lê window.GLYPHS pra glosar cada kanji da frase.
   Todas as frases usam SOMENTE kanji presentes no baralho
   (validado). Kana só nas partículas/terminações.
   tier: 'n5' · 'n4' · 'n3' · 'n2'
   ============================================================ */
const { useState: useFrState } = React;

const SENTENCES = [
  /* ── N5 ── */
  ['n5','私は本を読む。','watashi wa hon o yomu','Eu leio um livro.'],
  ['n5','母は魚を買う。','haha wa sakana o kau','Minha mãe compra peixe.'],
  ['n5','父は車で会社へ行く。','chichi wa kuruma de kaisha e iku','Meu pai vai à empresa de carro.'],
  ['n5','妹は赤い花が好きだ。','imōto wa akai hana ga suki da','Minha irmã caçula gosta de flores vermelhas.'],
  ['n5','夏に海へ行く。','natsu ni umi e iku','No verão eu vou ao mar.'],
  ['n5','友だちと店で茶を飲む。','tomodachi to mise de cha o nomu','Tomo chá com os amigos na loja.'],
  ['n5','雨の日は家で音楽を聞く。','ame no hi wa ie de ongaku o kiku','Em dias de chuva escuto música em casa.'],
  ['n5','犬は外で水を飲む。','inu wa soto de mizu o nomu','O cachorro bebe água lá fora.'],
  ['n5','姉は白い服を着る。','ane wa shiroi fuku o kiru','Minha irmã mais velha veste roupa branca.'],
  ['n5','今日は天気がいい。','kyō wa tenki ga ii','Hoje o tempo está bom.'],
  ['n5','一本の木が川のそばにある。','ippon no ki ga kawa no soba ni aru','Há uma árvore à beira do rio.'],
  ['n5','七月と八月は夏だ。','shichigatsu to hachigatsu wa natsu da','Julho e agosto são verão.'],
  ['n5','九時に十人が来る。','kuji ni juunin ga kuru','Às nove horas, dez pessoas vêm.'],
  ['n5','百円と千円を出す。','hyaku-en to sen-en o dasu','Pago com cem e mil ienes.'],
  ['n5','一万円で何が買えますか。','ichiman-en de nani ga kaemasu ka','O que posso comprar com dez mil ienes?'],
  ['n5','男の子が土の上に立つ。','otoko no ko ga tsuchi no ue ni tatsu','O menino fica de pé sobre a terra.'],
  ['n5','口で食べて、耳で聞く。','kuchi de tabete, mimi de kiku','Come pela boca e ouve pelos ouvidos.'],
  ['n5','右の手で書き、左の手で持つ。','migi no te de kaki, hidari no te de motsu','Escrevo com a mão direita e seguro com a esquerda.'],
  ['n5','心は体の中にある。','kokoro wa karada no naka ni aru','O coração está dentro do corpo.'],
  ['n5','森の中に川がある。','mori no naka ni kawa ga aru','Dentro da floresta há um rio.'],
  ['n5','火は赤くて明るい。','hi wa akakute akarui','O fogo é vermelho e brilhante.'],
  ['n5','東の空が明るくなる。','higashi no sora ga akaruku naru','O céu do leste clareia.'],
  ['n5','東と西と南と北がある。','higashi to nishi to minami to kita ga aru','Existem leste, oeste, sul e norte.'],
  ['n5','午後に空を見上げる。','gogo ni sora o miageru','À tarde olho para o céu.'],
  ['n5','毎週、電話で話す。','maishuu, denwa de hanasu','Toda semana falo ao telefone.'],
  ['n5','月曜日に電車で来る。','getsuyoubi ni densha de kuru','Na segunda-feira venho de trem.'],
  ['n5','高い山と長い川がある。','takai yama to nagai kawa ga aru','Há uma montanha alta e um rio longo.'],
  ['n5','半分に切る。','hanbun ni kiru','Corto ao meio.'],
  ['n5','外国語を話す。','gaikokugo o hanasu','Falo uma língua estrangeira.'],
  ['n5','出口と入口がある。','deguchi to iriguchi ga aru','Há saída e entrada.'],
  ['n5','家に帰って食べる。','ie ni kaette taberu','Volto para casa e como.'],
  ['n5','名前と年を書く。','namae to toshi o kaku','Escrevo o nome e a idade.'],
  ['n5','女の子と男の子が話す。','onna no ko to otoko no ko ga hanasu','A menina e o menino conversam.'],
  ['n5','二月と三月は春だ。','nigatsu to sangatsu wa haru da','Fevereiro e março são primavera.'],
  ['n5','大きい木の下に小さい花がある。','ookii ki no shita ni chiisai hana ga aru','Embaixo da árvore grande há uma flor pequena.'],
  ['n5','金曜日に休む。','kin-youbi ni yasumu','Descanso na sexta-feira.'],
  ['n5','足は体の下にある。','ashi wa karada no shita ni aru','Os pés ficam na parte de baixo do corpo.'],
  ['n5','少し話す。','sukoshi hanasu','Falo um pouco.'],
  ['n5','千の言葉より一つの行いだ。','sen no kotoba yori hitotsu no okonai da','Uma ação vale mais que mil palavras.'],
  ['n5','四月から六月まで春だ。','shigatsu kara rokugatsu made haru da','De abril a junho é primavera.'],
  ['n5','五月は雨が多い。','gogatsu wa ame ga ooi','Em maio, chove muito.'],
  ['n5','初めて一人で行く。','hajimete hitori de iku','Vou sozinho pela primeira vez.'],
  ['n5','他の人と話す。','hoka no hito to hanasu','Falo com outras pessoas.'],
  ['n5','先生に問いを出す。','sensei ni toi o dasu','Faço uma pergunta ao professor.'],
  ['n5','牛の肉を食べる。','ushi no niku o taberu','Como carne de vaca.'],
  ['n5','又、明日来る。','mata, ashita kuru','Volto amanhã de novo.'],
  ['n5','安い店に入る。','yasui mise ni hairu','Entro numa loja barata.'],
  ['n5','一時間は六十分だ。','ichijikan wa rokujuupun da','Uma hora tem sessenta minutos.'],
  ['n5','早く学校へ行く。','hayaku gakkō e iku','Vou para a escola cedo.'],
  ['n5','古い道と新しい駅がある。','furui michi to atarashii eki ga aru','Há um caminho antigo e uma estação nova.'],
  ['n5','秋になって字を知る。','aki ni natte ji o shiru','No outono aprendo os caracteres.'],

  /* ── N4 ── */
  ['n4','朝早く起きて、山の道を歩く。','asa hayaku okite, yama no michi o aruku','De manhã cedo eu acordo e caminho pela trilha da montanha.'],
  ['n4','先生は教室で漢字を教える。','sensei wa kyōshitsu de kanji o oshieru','O professor ensina kanji na sala de aula.'],
  ['n4','母は米を買って料理を作る。','haha wa kome o katte ryōri o tsukuru','Minha mãe compra arroz e prepara a comida.'],
  ['n4','父は新しい家を建てる。','chichi wa atarashii ie o tateru','Meu pai constrói uma casa nova.'],
  ['n4','秋になると林が赤くなる。','aki ni naru to hayashi ga akaku naru','Quando chega o outono, o bosque fica vermelho.'],
  ['n4','古い店の前に人が多い。','furui mise no mae ni hito ga ōi','Há muita gente em frente à loja antiga.'],
  ['n4','弟は学校で文を書く。','otōto wa gakkō de bun o kaku','Meu irmão mais novo escreve um texto na escola.'],
  ['n4','妹は歌を歌うのが好きだ。','imōto wa uta o utau no ga suki da','Minha irmã caçula gosta de cantar.'],
  ['n4','駅の近くに新しい店がある。','eki no chikaku ni atarashii mise ga aru','Perto da estação há uma loja nova.'],
  ['n4','時間を時計で見る。','jikan o tokei de miru','Vejo as horas no relógio.'],
  ['n4','田んぼで米を作る。','tanbo de kome o tsukuru','Cultivo arroz no arrozal.'],
  ['n4','目で色を見る。','me de iro o miru','Vejo as cores com os olhos.'],
  ['n4','困った時は自分で考える。','komatta toki wa jibun de kangaeru','Em apuros, penso por conta própria.'],
  ['n4','門の前に石がある。','mon no mae ni ishi ga aru','Há uma pedra em frente ao portão.'],
  ['n4','衣を着て家に住む。','koromo o kite ie ni sumu','Visto roupa e moro em casa.'],
  ['n4','刀を売る店がある。','katana o uru mise ga aru','Há uma loja que vende espadas.'],
  ['n4','矢を持って走る。','ya o motte hashiru','Corro segurando a flecha.'],
  ['n4','果物を台の上に置く。','kudamono o dai no ue ni oku','Coloco as frutas em cima da mesa.'],
  ['n4','代わりの品を出す。','kawari no shina o dasu','Apresento um item substituto.'],
  ['n4','和食と洋食がある。','washoku to yōshoku ga aru','Há comida japonesa e comida ocidental.'],
  ['n4','交通を止める。','kōtsū o tomeru','Paro o trânsito.'],
  ['n4','馬が広い野を走る。','uma ga hiroi no o hashiru','O cavalo corre pelo campo amplo.'],
  ['n4','工事が始まる。','kōji ga hajimaru','A obra começa.'],
  ['n4','豆を食べると元気になる。','mame o taberu to genki ni naru','Quando como feijão fico com energia.'],
  ['n4','内に光がある。','uchi ni hikari ga aru','Há luz no interior.'],
  ['n4','同じ方向に向かう。','onaji hōkō ni mukau','Vamos na mesma direção.'],
  ['n4','青い鳥が木の上にいる。','aoi tori ga ki no ue ni iru','Um pássaro azul está no topo da árvore.'],
  ['n4','冬は雪が多い。','fuyu wa yuki ga ōi','No inverno há muita neve.'],
  ['n4','台所で飯を作る。','daidokoro de meshi o tsukuru','Preparo a refeição na cozinha.'],
  ['n4','池に太い魚がいる。','ike ni futoi sakana ga iru','Há peixes gordos na lagoa.'],
  ['n4','正しい答えを出す。','tadashii kotae o dasu','Dou a resposta correta.'],
  ['n4','短い文を書く。','mijikai bun o kaku','Escrevo uma frase curta.'],
  ['n4','黒い服を着た親が待つ。','kuroi fuku o kita oya ga matsu','Os pais vestidos de preto esperam.'],
  ['n4','夏は虫が多い。','natsu wa mushi ga ōi','No verão há muitos insetos.'],
  ['n4','予定を立てる。','yotei o tateru','Estabeleço um plano.'],
  ['n4','今日は用事がある。','kyō wa yōji ga aru','Hoje tenho assuntos a resolver.'],
  ['n4','広場の中央に立つ。','hiroba no chūō ni tatsu','Fico em pé no centro da praça.'],
  ['n4','己を知ることが大切だ。','onore o shiru koto ga taisetsu da','Conhecer a si mesmo é importante.'],
  ['n4','羊の毛で服を作る。','hitsuji no ke de fuku o tsukuru','Faço roupas com lã de ovelha.'],
  ['n4','この由来を知る。','kono yurai o shiru','Conheço a origem disso.'],
  ['n4','京都へ旅する。','Kyōto e tabi suru','Viajo para Kyoto.'],
  ['n4','夜に業を終える。','yoru ni gyō o oeru','À noite termino o trabalho.'],
  ['n4','発表の表を書く。','happyō no hyō o kaku','Escrevo a tabela para a apresentação.'],
  ['n4','竹の橋がある。','take no hashi ga aru','Há uma ponte de bambu.'],
  ['n4','県の銀行に行く。','ken no ginkō ni iku','Vou ao banco da prefeitura.'],
  ['n4','鉄の門がある。','tetsu no mon ga aru','Há um portão de ferro.'],
  ['n4','様子を見る。','yōsu o miru','Observo a situação.'],
  ['n4','屋根が高い建物がある。','yane ga takai tatemono ga aru','Há um prédio com telhado alto.'],
  ['n4','毎度、駅で待つ。','maido, eki de matsu','Espero na estação sempre.'],
  ['n4','昼に野の花を見る。','hiru ni no no hana o miru','Ao meio-dia vejo as flores do campo.'],
  ['n4','仕事が終わる。','shigoto ga owaru','O trabalho termina.'],
  ['n4','習字を練習する。','shūji o renshū suru','Pratico caligrafia.'],
  ['n4','場所を決める。','basho o kimeru','Decido o lugar.'],
  ['n4','去年、海外へ行った。','kyonen, kaigai e itta','Ano passado fui para o exterior.'],
  ['n4','部屋に物を運ぶ。','heya ni mono o hakobu','Levo as coisas para o quarto.'],
  ['n4','みんなが集まって話す。','minna ga atsumatte hanasu','Todo mundo se reúne e conversa.'],
  ['n4','題名を書く。','daimei o kaku','Escrevo o título.'],
  ['n4','顔の色を見る。','kao no iro o miru','Olho a cor do rosto.'],
  ['n4','紙に絵を書く。','kami ni e o kaku','Desenho em papel.'],
  ['n4','皿に料理を乗せる。','sara ni ryōri o noseru','Sirvo a comida no prato.'],
  ['n4','申し出を受ける。','mōshide o ukeru','Aceito a proposta.'],
  ['n4','皮を切って果物を食べる。','kawa o kitte kudamono o taberu','Descasco e como a fruta.'],
  ['n4','曲を書いて発表する。','kyoku o kaite happyō suru','Componho uma música e a apresento.'],
  ['n4','写真を見て思い出す。','shashin o mite omoidasu','Olho a foto e me lembro.'],
  ['n4','幸せな身になる。','shiawase na mi ni naru','Torno-me uma pessoa feliz.'],
  ['n4','平らな面を作る。','taira na men o tsukuru','Crio uma superfície plana.'],
  ['n4','両手で持つ。','ryōte de motsu','Seguro com as duas mãos.'],
  ['n4','暗い夜が来る。','kurai yoru ga kuru','A noite escura chega.'],
  ['n4','委員会に入る。','iinkai ni hairu','Entro no comitê.'],
  ['n4','子どもを育てる。','kodomo o sodateru','Crio meus filhos.'],
  ['n4','英語を勉強する。','eigo o benkyō suru','Estudo inglês.'],
  ['n4','温かい館に入る。','atatakai yakata ni hairu','Entro num salão aconchegante.'],
  ['n4','急いで橋を通る。','isoide hashi o tōru','Passo pela ponte com pressa.'],
  ['n4','宮の前で待つ。','miya no mae de matsu','Espero em frente ao palácio.'],
  ['n4','局の人に話す。','kyoku no hito ni hanasu','Falo com a pessoa da repartição.'],
  ['n4','苦しい時も止まらない。','kurushii toki mo tomaranai','Não paro mesmo nos momentos difíceis.'],
  ['n4','具体的に言う。','gutaiteki ni iu','Digo de forma concreta.'],
  ['n4','君に話がある。','kimi ni hanashi ga aru','Tenho algo a dizer para você.'],
  ['n4','係の人を呼ぶ。','kakari no hito o yobu','Chamo o responsável.'],
  ['n4','軽い物を持つ。','karui mono o motsu','Carrego objetos leves.'],
  ['n4','号を決めて発表する。','gō o kimete happyō suru','Decido o número e anuncio.'],
  ['n4','祭りに行く。','matsuri ni iku','Vou ao festival.'],
  ['n4','指で地図を指す。','yubi de chizu o sasu','Aponto o mapa com o dedo.'],
  ['n4','歯が弱い。','ha ga yowai','O dente está fraco.'],
  ['n4','次の駅で止まる。','tsugi no eki de tomaru','Para na próxima estação.'],
  ['n4','実は知っていた。','jitsu wa shitte ita','Na verdade, eu já sabia.'],
  ['n4','守る力を持つ。','mamoru chikara o motsu','Tenho a força de proteger.'],
  ['n4','酒を少し飲む。','sake o sukoshi nomu','Bebo um pouco de saquê.'],
  ['n4','受け取った物を開く。','uketotta mono o hiraku','Abro o que recebi.'],
  ['n4','百円を拾う。','hyakuen o hirou','Pego cem ienes do chão.'],
  ['n4','宿に泊まる。','yado ni tomaru','Me hospedo numa pousada.'],
  ['n4','暑い夏が来た。','atsui natsu ga kita','O verão quente chegou.'],
  ['n4','助けを求める。','tasuke o motomeru','Peço ajuda.'],
  ['n4','消えた光を見る。','kieta hikari o miru','Vejo a luz que desapareceu.'],
  ['n4','商人が店を開く。','shōnin ga mise o hiraku','O comerciante abre a loja.'],
  ['n4','新しい章を読む。','atarashii shō o yomu','Leio o novo capítulo.'],
  ['n4','植物を育てる。','shokubutsu o sodateru','Cultivo plantas.'],
  ['n4','神社に行く。','jinja ni iku','Vou ao santuário.'],
  ['n4','深い川を見る。','fukai kawa o miru','Vejo o rio fundo.'],
  ['n4','整理して片付ける。','seiri shite katazukeru','Organizo e arrumo tudo.'],
  ['n4','昔話を知っている。','mukashibanashi o shitte iru','Conheço os contos antigos.'],
  ['n4','全員が集まる。','zen’in ga atsumaru','Todos se reúnem.'],
  ['n4','相手を思って話す。','aite o omotte hanasu','Falo pensando no outro.'],
  ['n4','息を吸う。','iki o suu','Inspiro.'],
  ['n4','速く走る人がいる。','hayaku hashiru hito ga iru','Há uma pessoa que corre rápido.'],
  ['n4','手を打って決める。','te o utte kimeru','Bato as mãos e decido.'],
  ['n4','第一の発表をする。','daiichi no happyō o suru','Faço a primeira apresentação.'],
  ['n4','炭火で肉を焼く。','sumibe de niku o yaku','Grelho carne no carvão.'],
  ['n4','会談に出る。','kaidan ni deru','Participo de uma reunião.'],
  ['n4','柱に帳面をかける。','hashira ni chōmen o kakeru','Pendurei o caderno no pilar.'],
  ['n4','調べて答える。','shirabete kotaeru','Pesquiso e respondo.'],
  ['n4','庭に池がある。','niwa ni ike ga aru','Há uma lagoa no jardim.'],
  ['n4','笛を吹く。','fue o fuku','Toco flauta.'],
  ['n4','点を取る。','ten o toru','Marco pontos.'],
  ['n4','ボールを投げる。','bōru o nageru','Arremesso a bola.'],
  ['n4','山に登る。','yama ni noboru','Escalo a montanha.'],
  ['n4','島に行く。','shima ni iku','Vou para a ilha.'],
  ['n4','お湯に入る。','oyu ni hairu','Entro na água quente.'],
  ['n4','同じ等級がある。','onaji tōkyū ga aru','Existe o mesmo nível.'],
  ['n4','童話を読む。','dōwa o yomu','Leio um conto de fadas.'],
  ['n4','農家で働く。','nōka de hataraku','Trabalho numa fazenda.'],
  ['n4','波が来る。','nami ga kuru','As ondas chegam.'],
  ['n4','物を配達する。','mono o haitatsu suru','Entrego as coisas.'],
  ['n4','倍の力を出す。','bai no chikara o dasu','Mostro o dobro da força.'],
  ['n4','箱に入れて送る。','hako ni irete okuru','Coloco na caixa e mando.'],
  ['n4','坂を登る。','saka o noboru','Subo a ladeira.'],
  ['n4','板に文字を書く。','ita ni moji o kaku','Escrevo letras na tábua.'],
  ['n4','悲しい話を聞く。','kanashii hanashi o kiku','Ouço uma história triste.'],
  ['n4','美しい色の花がある。','utsukushii iro no hana ga aru','Há flores de cores bonitas.'],
  ['n4','鼻が高い人がいる。','hana ga takai hito ga iru','Há pessoas de nariz comprido.'],
  ['n4','筆で字を書く。','fude de ji o kaku','Escrevo caracteres com pincel.'],
  ['n4','氷水を飲む。','kōrisui o nomu','Bebo água gelada.'],
  ['n4','秒針が動く。','byōshin ga ugoku','O ponteiro de segundos se move.'],
  ['n4','試合に負ける。','shiai ni makeru','Perco na competição.'],
  ['n4','福を呼ぶ。','fuku o yobu','Chamo a boa sorte.'],
  ['n4','放課後に遊ぶ。','hōkago ni asobu','Brinco depois das aulas.'],
  ['n4','命を守る。','inochi o mamoru','Protejo a vida.'],
  ['n4','役に立つ人になる。','yaku ni tatsu hito ni naru','Torno-me uma pessoa útil.'],
  ['n4','油で料理する。','abura de ryōri suru','Cozinho com óleo.'],
  ['n4','有名な場所へ行く。','yūmei na basho e iku','Vou a um lugar famoso.'],
  ['n4','陽が出る場所がいい。','hi ga deru basho ga ii','O lugar onde o sol aparece é bom.'],
  ['n4','川が流れる。','kawa ga nagareru','O rio flui.'],
  ['n4','緑の野原がある。','midori no nohara ga aru','Há um campo verde.'],
  ['n4','礼を言う。','rei o iu','Agradeço.'],
  ['n4','列に並ぶ。','retsu ni narabu','Filo na fila.'],
  ['n4','本を借りる。','hon o kariru','Pego um livro emprestado.'],
  ['n4','公園で遊ぶ。','kōen de asobu','Brinco no parque.'],
  ['n4','別の道を行く。','betsu no michi o iku','Vou por outro caminho.'],
  ['n4','悪い人から逃げる。','warui hito kara nigeru','Fujo de pessoas más.'],
  ['n4','町を歩いて見る。','machi o aruite miru','Caminho pela cidade observando.'],
  ['n4','絵を画用紙に書く。','e o gayōshi ni kaku','Desenho no papel de desenho.'],
  ['n4','本を貸す。','hon o kasu','Empresto o livro.'],
  ['n4','質問に答える。','shitsumon ni kotaeru','Respondo à pergunta.'],
  ['n4','試験を受ける。','shiken o ukeru','Faço o exame.'],
  ['n4','想いを伝える。','omoi o tsutaeru','Transmito meus sentimentos.'],
  ['n4','追いかけて止める。','oikakete tomeru','Corro atrás e paro.'],
  ['n4','対話をする。','taiwa o suru','Faço diálogo.'],
  ['n4','使い方を教える。','tsukaikata o oshieru','Ensino como usar.'],
  ['n4','勝つために練習する。','katsu tame ni renshū suru','Treino para vencer.'],

  ['n4','畑で花を作る。','hatake de hana o tsukuru','Cultivo flores no campo.'],
  ['n4','里山の岸に行く。','satoyama no kishi ni iku','Vou à beira do monte rural.'],
  ['n4','不可だと言う。','fuka da to iu','Diz que não é permitido.'],
  ['n4','区の食堂で食べる。','ku no shokudō de taberu','Como no refeitório do distrito.'],
  ['n4','氏名を書く。','shimei o kaku','Escrevo o nome completo.'],
  ['n4','研究の期待が高い。','kenkyū no kitai ga takai','A expectativa pela pesquisa é alta.'],
  ['n4','丁目に住む。','chouome ni sumu','Moro no quarteirão.'],
  ['n4','死んだ木がある。','shinda ki ga aru','Há uma árvore morta.'],
  ['n4','位を上げる。','kurai o ageru','Elevo o posto.'],

  /* ── N3 ── */
  ['n3','炎天下で水を飲む。','enten ka de mizu o nomu','Bebo água sob o calor intenso.'],
  ['n3','夕食を食べる。','yūshoku o taberu','Como o jantar.'],
  ['n3','士が戦いを信じる。','samurai ga tatakai o shinjiru','O guerreiro acredita na batalha.'],
  ['n3','欠点を認める。','ketten o mitomeru','Reconheço os defeitos.'],
  ['n3','件名を書いて送る。','kenmei o kaite okuru','Escrevo o assunto e mando.'],
  ['n3','科学の利点を知る。','kagaku no riten o shiru','Conheço as vantagens da ciência.'],
  ['n3','化学物質を注意する。','kagaku busshitsu o chūi suru','Fico atento às substâncias químicas.'],
  ['n3','結果を告げる。','kekka o tsugeru','Anuncio o resultado.'],
  ['n3','岩の上に立つ。','iwa no ue ni tatsu','Fico de pé na rocha.'],
  ['n3','夫が家に帰る。','otto ga ie ni kaeru','O marido volta para casa.'],
  ['n3','首を動かす。','kubi o ugokasu','Mexo o pescoço.'],
  ['n3','貝を海で集める。','kai o umi de atsumeru','Coleto conchas no mar.'],
  ['n3','玉が光る。','tama ga hikaru','A joia brilha.'],
  ['n3','寺に行って静かに過ごす。','tera ni itte shizuka ni sugosu','Vou ao templo e passo o tempo em silêncio.'],
  ['n3','介護の仕事をする。','kaigo no shigoto o suru','Faço trabalho de cuidado.'],
  ['n3','吾が道を行く。','ware ga michi o iku','Sigo meu caminho.'],
  ['n3','占いで未来を知る。','uranai de mirai o shiru','Conheço o futuro pela adivinhação.'],
  ['n3','反対意見を言う。','hantai iken o iu','Expresso minha opinião contrária.'],
  ['n3','式典に参加する。','shikiten ni sanka suru','Participo da cerimônia.'],
  ['n3','特別な穴がある。','tokubetsu na ana ga aru','Há um buraco especial.'],
  ['n3','糸で物を作る。','ito de mono o tsukuru','Faço coisas com fio.'],
  ['n3','羽が白い鳥がいる。','hane ga shiroi tori ga iru','Há um pássaro de penas brancas.'],
  ['n3','各地を旅する。','kakuchi o tabisuru','Viajo por várias regiões.'],
  ['n3','至る所に花がある。','itaru tokoro ni hana ga aru','Há flores por toda parte.'],
  ['n3','弓を引く。','yumi o hiku','Puxo o arco.'],
  ['n3','映画を見る。','eiga o miru','Assisto ao filme.'],
  ['n3','細かい点に注意する。','komakai ten ni chūi suru','Presto atenção nos detalhes.'],
  ['n3','落ち葉が道に落ちる。','ochiba ga michi ni ochiru','Folhas caídas caem no caminho.'],
  ['n3','族の人々が集まる。','zoku no hitobito ga atsumaru','As pessoas do clã se reúnem.'],
  ['n3','転んで立ち上がる。','koronde tachiagaru','Tropeço e me levanto.'],
  ['n3','道が進む方向に向かう。','michi ga susumu hōkō ni mukau','O caminho vai na direção que avançamos.'],
  ['n3','是非、来てください。','zehi, kite kudasai','Por favor, venha com certeza.'],
  ['n3','頭を使って考える。','atama o tsukatte kangaeru','Uso a cabeça para pensar.'],
  ['n3','組を作って動く。','kumi o tsukutte ugoku','Formo um grupo e me movo.'],
  ['n3','約を結ぶ。','yaku o musubu','Firmo um acordo.'],
  ['n3','手紙を返す。','tegami o kaesu','Devolvo a carta.'],
  ['n3','遠い所まで完走する。','tōi tokoro made kansō suru','Termino a corrida até um lugar distante.'],
  ['n3','薬を飲んで休む。','kusuri o nonde yasumu','Tomo remédio e descanso.'],
  ['n3','舟で川を行く。','fune de kawa o iku','Vou de barco pelo rio.'],
  ['n3','角を曲がる。','kado o magaru','Dobro a esquina.'],
  ['n3','黄色い花がある。','kiiroi hana ga aru','Há flores amarelas.'],
  ['n3','共に行く。','tomo ni iku','Vou junto.'],
  ['n3','以上の物がある。','ijō no mono ga aru','Há o que foi dito acima.'],
  ['n3','魚を干す。','sakana o hosu','Ponho o peixe para secar.'],
  ['n3','永遠の道がある。','eien no michi ga aru','Há um caminho eterno.'],
  ['n3','失った物を取り戻す。','ushinatta mono o torimodosу','Recupero o que perdi.'],
  ['n3','歴史書を読む。','rekishi sho o yomu','Leio livros de história.'],
  ['n3','弁解する。','benkai suru','Me explico.'],
  ['n3','余った物を使う。','amatta mono o tsukau','Uso as sobras.'],
  ['n3','大きさを比べる。','ookisa o kuraberu','Comparo os tamanhos.'],
  ['n3','危ない場所を知る。','abunai basho o shiru','Sei dos lugares perigosos.'],
  ['n3','久しぶりに会う。','hisashiburi ni au','Me encontro depois de muito tempo.'],
  ['n3','再び始める。','futatabi hajimeru','Começo de novo.'],
  ['n3','巻物を見る。','makimono o miru','Vejo o pergaminho.'],
  ['n3','任務を果たす。','ninmu o hatasu','Cumpro minha missão.'],
  ['n3','武士がいる。','bushi ga iru','Há um guerreiro.'],
  ['n3','居場所を見つける。','ibasho o mitsukeru','Encontro meu lugar.'],
  ['n3','旧友に会う。','kyūyū ni au','Encontro um velho amigo.'],
  ['n3','在庫がある。','zaikō ga aru','Há estoque.'],
  ['n3','素直な心を持つ。','sunao na kokoro o motsu','Tenho um coração simples e honesto.'],
  ['n3','祖父母に会いに行く。','sofubo ni ai ni iku','Vou visitar os avós.'],
  ['n3','個人の物を守る。','kojin no mono o mamoru','Protejo as coisas pessoais.'],
  ['n3','庫に物を入れる。','kura ni mono o ireru','Coloco as coisas no depósito.'],
  ['n3','古い故事を知る。','furui koji o shiru','Conheço as anedotas antigas.'],
  ['n3','効果がある。','kōka ga aru','Tem efeito.'],
  ['n3','厚い本を読む。','atsui hon o yomu','Leio um livro grosso.'],
  ['n3','港に舟が来る。','minato ni fune ga kuru','O barco chega ao porto.'],
  ['n3','航空機で行く。','kōkūki de iku','Vou de avião.'],
  ['n3','横に進む。','yoko ni susumu','Avanço para o lado.'],
  ['n3','桜の花を見る。','sakura no hana o miru','Vejo as flores de cerejeira.'],
  ['n3','液体を入れる。','ekitai o ireru','Coloco o líquido.'],
  ['n3','演技をする。','engi o suru','Atuo.'],
  ['n3','山を越えて行く。','yama o koete iku','Cruzo a montanha e vou.'],
  ['n3','億円を使う。','okuyen o tsukau','Uso um bilhão de ienes.'],
  ['n3','価格を見る。','kakaku o miru','Vejo o preço.'],
  ['n3','河原を歩く。','kawara o aruku','Caminho pelo leito do rio.'],
  ['n3','過去を知る。','kako o shiru','Conheço o passado.'],
  ['n3','問題を解決する。','mondai o kaiketsu suru','Resolvo o problema.'],
  ['n3','格式を守る。','kakushiki o mamoru','Sigo a formalidade.'],
  ['n3','確認して進む。','kakunin shite susumu','Confirmo e avanço.'],
  ['n3','額を見る。','gaku o miru','Vejo o quadro.'],
  ['n3','観光地に行く。','kankōchi ni iku','Vou ao ponto turístico.'],
  ['n3','関係がある。','kankei ga aru','Há relação.'],
  ['n3','願いを持つ。','negai o motsu','Tenho um desejo.'],
  ['n3','喜んで行く。','yorokonde iku','Vou com alegria.'],
  ['n3','規律を守る。','kiritsu o mamoru','Sigo a disciplina.'],
  ['n3','寄付をする。','kifu o suru','Faço doação.'],
  ['n3','技術を使う。','gijutsu o tsukau','Uso tecnologia.'],
  ['n3','義務を果たす。','gimu o hatasu','Cumpro meu dever.'],
  ['n3','逆の方向に行く。','gyaku no hōkō ni iku','Vou na direção oposta.'],
  ['n3','許可を取る。','kyoka o toru','Obtenho permissão.'],
  ['n3','境界を決める。','kyōkai o kimeru','Determino o limite.'],
  ['n3','鏡を見る。','kagami o miru','Olho no espelho.'],
  ['n3','競争する。','kyōsō suru','Compito.'],
  ['n3','極限を知る。','kyokugen o shiru','Conheço o limite extremo.'],
  ['n3','軍人が戦う。','gunjin ga tatakau','O soldado luta.'],
  ['n3','郡の地図を持つ。','gun no chizu o motsu','Tenho o mapa do condado.'],
  ['n3','経験がある。','keiken ga aru','Tenho experiência.'],
  ['n3','未来を考える。','mirai o kangaeru','Penso no futuro.'],
  ['n3','直接話す。','chokusetsu hanasu','Falo diretamente.'],
  ['n3','谷を歩く。','tani o aruku','Caminho pelo vale.'],
  ['n3','単語を学ぶ。','tango o manabu','Aprendo palavras.'],
  ['n3','刃物を持つ。','hamono o motsu','Seguro um objeto cortante.'],
  ['n3','忍ぶ心がある。','shinobu kokoro ga aru','Tenho um coração que suporta.'],
  ['n3','政治を学ぶ。','seiji o manabu','Estudo política.'],
  ['n3','法律を知る。','hōritsu o shiru','Conheço as leis.'],
  ['n3','議会で話す。','gikai de hanasu','Falo no parlamento.'],
  ['n3','感動する。','kandō suru','Me emociono.'],
  ['n3','量が減る。','ryō ga heru','A quantidade diminui.'],
  ['n3','球を投げる。','tama o nageru','Arremesso a bola.'],
  ['n3','人を救う。','hito o sukuu','Salvo uma pessoa.'],
  ['n3','例を見る。','rei o miru','Vejo o exemplo.'],
  ['n3','原因を考える。','gen’in o kangaeru','Penso na causa.'],
  ['n3','容姿がいい。','yōshi ga ii','Tem boa aparência.'],
  ['n3','海水浴をする。','kaisuiyoku o suru','Tomo banho de mar.'],
  ['n3','欲しい物がある。','hoshii mono ga aru','Há algo que quero.'],
  ['n3','種を植える。','tane o ueru','Planto sementes.'],
  ['n3','季ごとに変わる。','ki goto ni kawaru','Muda a cada estação.'],
  ['n3','移動する。','idō suru','Me movo.'],
  ['n3','念入りに調べる。','neniri ni shiraberu','Verifico com cuidado.'],
  ['n3','情報を集める。','jōhō o atsumeru','Coleto informações.'],
  ['n3','清水を飲む。','shimizu o nomu','Bebo água pura.'],
  ['n3','晴れた日に出かける。','hareta hi ni dekakeru','Saio num dia de sol.'],
  ['n3','静かな場所で休む。','shizuka na basho de yasumu','Descanso num lugar silencioso.'],
  ['n3','制服を着る。','seifuku o kiru','Visto o uniforme.'],
  ['n3','製品を作る。','seihin o tsukuru','Fabrico produtos.'],
  ['n3','状況を見る。','jōkyō o miru','Observo a situação.'],
  ['n3','査定をする。','satei o suru','Faço uma avaliação.'],
  ['n3','矛を持つ。','hoko o motsu','Seguro uma lança.'],
  ['n3','能力がある。','nōryoku ga aru','Tenho capacidade.'],
  ['n3','票を入れる。','hyō o ireru','Deposito meu voto.'],
  ['n3','泉を見つける。','izumi o mitsukeru','Encontro uma fonte.'],
  ['n3','充分に休む。','jūbun ni yasumu','Descanso suficientemente.'],
  ['n3','官職を持つ。','kanshoku o motsu','Tenho um cargo público.'],
  ['n3','費用がかかる。','hiyō ga kakaru','Custa dinheiro.'],
  ['n3','仏像を見る。','butsuzō o miru','Vejo uma estátua de Buda.'],
  ['n3','報告する。','hōkoku suru','Faço relatório.'],
  ['n3','性格が良い。','seikaku ga yoi','O caráter é bom.'],
  ['n3','産業を守る。','sangyō o mamoru','Protejo a indústria.'],
  ['n3','常識がある。','jōshiki ga aru','Tenho bom senso.'],
  ['n3','賞を取る。','shō o toru','Ganho o prêmio.'],
  ['n3','権利を持つ。','kenri o motsu','Tenho direitos.'],
  ['n3','務めを果たす。','tsutome o hatasu','Cumpro meu dever.'],
  ['n3','職場で給料をもらう。','shokuba de kyūryō o morau','Recebo meu salário no trabalho.'],
  ['n3','問題が済む。','mondai ga sumu','O problema se resolve.'],
  ['n3','資料を集める。','shiryō o atsumeru','Coleto material.'],
  ['n3','姿を見せる。','sugata o miseru','Mostro minha forma.'],
  ['n3','類似点がある。','ruijiten ga aru','Há pontos similares.'],
  ['n3','型を作る。','kata o tsukuru','Crio um molde.'],
  ['n3','態度を決める。','taido o kimeru','Decido minha atitude.'],
  ['n3','現在を大切にする。','genzai o taisetsu ni suru','Valorizo o presente.'],
  ['n3','留学する。','ryūgaku suru','Estudo no exterior.'],
  ['n3','備えて行動する。','sonaete kōdō suru','Ajo com preparo.'],
  ['n3','協力する。','kyōryoku suru','Coopero.'],
  ['n3','最後まで行く。','saigo made iku','Vou até o fim.'],
  ['n3','健康を守る。','kenkō o mamoru','Cuido da saúde.'],
  ['n3','精神を強くする。','seishin o tsuyoku suru','Fortaleço o espírito.'],
  ['n3','標識を見る。','hyōshiki o miru','Vejo a sinalização.'],
  ['n3','源に戻る。','minamoto ni modoru','Volto à origem.'],
  ['n3','条件を決める。','jōken o kimeru','Determino as condições.'],
  ['n3','環境を守る。','kankyō o mamoru','Cuido do meio ambiente.'],
  ['n3','統一する。','tōitsu suru','Unifico.'],
  ['n3','新しい場所に慣れる。','atarashii basho ni nareru','Me acostumo ao novo lugar.'],
  ['n3','景色を見る。','keshiki o miru','Vejo a paisagem.'],
  ['n3','自然の中にいる。','shizen no naka ni iru','Estou na natureza.'],
  ['n3','木が燃える。','ki ga moeru','A madeira queima.'],
  ['n3','湖を見る。','mizūmi o miru','Vejo o lago.'],
  ['n3','湿気が多い。','shikke ga ōi','Há muita umidade.'],
  ['n3','災害に備える。','saigai ni sonaeru','Me preparo para desastres.'],
  ['n3','害を防ぐ。','gai o fusegu','Previno danos.'],
  ['n3','障害がある。','shōgai ga aru','Há obstáculo.'],
  ['n3','設備を使う。','setsubi o tsukau','Uso as instalações.'],
  ['n3','記者になる。','kisha ni naru','Me torno jornalista.'],
  ['n3','物が壊れる。','mono ga kowareru','A coisa quebra.'],
  ['n3','保護する。','hogo suru','Protejo.'],
  ['n3','管理する。','kanri suru','Gerencio.'],
  ['n3','営業する。','eigyō suru','Realizo negócios.'],
  ['n3','数を数える。','kazu o kazoeru','Conto os números.'],
  ['n3','公園を散歩する。','kōen o sanpo suru','Passeio no parque.'],
  ['n3','物が残る。','mono ga nokoru','As coisas sobram.'],
  ['n3','形が変わる。','katachi ga kawaru','A forma muda.'],
  ['n3','群れを作る。','mure o tsukuru','Formo um bando.'],
  ['n3','一句を作る。','ikku o tsukuru','Crio um haiku.'],
  ['n3','固い物がある。','katai mono ga aru','Há algo duro.'],
  ['n3','眼鏡をかける。','megane o kakeru','Coloco os óculos.'],
  ['n3','検査する。','kensa suru','Faço inspeção.'],
  ['n3','構成を調べる。','kōsei o shiraberu','Verifico a composição.'],
  ['n3','講義を聞く。','kōgi o kiku','Ouço a palestra.'],
  ['n3','混乱する。','konran suru','Me confundo.'],
  ['n3','結婚する。','kekkon suru','Me caso.'],
  ['n3','手を押す。','te o osu','Empurro com a mão.'],
  ['n3','汚れを取る。','yogore o toru','Tiro a sujeira.'],
  ['n3','快晴の日がある。','kaisei no hi ga aru','Há dias de céu limpo.'],
  ['n3','記念日を知る。','kinennichi o shiru','Conheço a data comemorativa.'],
  ['n3','紀元を知る。','kigen o shiru','Conheço a era.'],
  ['n3','訓練する。','kunren suru','Treino.'],
  ['n3','均等に分ける。','kintō ni wakeru','Divido igualmente.'],
  ['n3','禁止する。','kinshi suru','Proíbo.'],
  ['n3','勤める。','tsutomeru','Trabalho.'],
  ['n3','志を持つ。','kokorozashi o motsu','Tenho aspiração.'],
  ['n3','師に学ぶ。','shi ni manabu','Aprendo com o mestre.'],
  ['n3','児童を守る。','jidō o mamoru','Protejo as crianças.'],
  ['n3','謝る。','ayamaru','Me desculpo.'],
  ['n3','趣味を楽しむ。','shumi o tanoshimu','Aproveito meu hobby.'],
  ['n3','収入がある。','shūnyū ga aru','Tenho renda.'],
  ['n3','祝日に休む。','shukujitsu ni yasumu','Descanso no feriado.'],
  ['n3','順番を守る。','junban o mamoru','Respeito a ordem.'],
  ['n3','処理する。','shori suru','Processo.'],
  ['n3','徐々に進む。','jojo ni susumu','Avanço gradualmente.'],
  ['n3','傷を治す。','kizu o naosu','Curo o ferimento.'],
  ['n3','唱える。','tonaeru','Canto / Proclamo.'],
  ['n3','招待する。','shōtai suru','Convido.'],
  ['n3','照らす光がある。','terasu hikari ga aru','Há uma luz que ilumina.'],
  ['n3','笑顔で話す。','egao de hanasu','Falo com sorriso no rosto.'],
  ['n3','象を見る。','zō o miru','Vejo o elefante.'],
  ['n3','振り返る。','furikaeru','Olho para trás.'],
  ['n3','震える体がある。','furueru karada ga aru','Há um corpo que treme.'],
  ['n3','我を忘れる。','ware o wasureru','Me perco em algo.'],
  ['n3','与える喜びがある。','ataeru yorokobi ga aru','Há alegria em dar.'],
  ['n3','幼い子がいる。','osanai ko ga iru','Há uma criança pequena.'],
  ['n3','泳いで対岸に行く。','oyoide taigan ni iku','Nado até a outra margem.'],
  ['n3','暖かい日がある。','atatakai hi ga aru','Há dias quentes.'],
  ['n3','応援する。','ōen suru','Torço / Apoio.'],
  ['n3','往復する。','ōfuku suru','Faço a ida e volta.'],
  ['n3','恩を感じる。','on o kanjiru','Sinto gratidão.'],
  ['n3','改める。','aratameru','Reformulo.'],
  ['n3','灰色の空がある。','haiiro no sora ga aru','Há um céu cinza.'],
  ['n3','割れた物がある。','wareta mono ga aru','Há algo quebrado.'],
  ['n3','活動する。','katsudō suru','Atuo.'],
  ['n3','機会を使う。','kikai o tsukau','Uso a oportunidade.'],
  ['n3','及ぶ力がある。','oyobu chikara ga aru','Há força que alcança.'],
  ['n3','胸が高鳴る。','mune ga takanaru','O coração acelera.'],
  ['n3','芸術を楽しむ。','geijutsu o tanoshimu','Aprecio a arte.'],
  ['n3','劇を見る。','geki o miru','Vejo a peça teatral.'],
  ['n3','血が出る。','chi ga deru','Sai sangue.'],
  ['n3','誤りを直す。','ayamari o naosu','Corrijo o erro.'],
  ['n3','孝行をする。','kōkō o suru','Sou filho dedicado.'],
  ['n3','江の水が多い。','kō no mizu ga ōi','O estuário tem muita água.'],
  ['n3','皇室に関心がある。','kōshitsu ni kanshin ga aru','Tenho interesse na família imperial.'],
  ['n3','亡くなった人を思う。','nakunatta hito o omou','Penso nas pessoas que se foram.'],
  ['n3','必要な物を用意する。','hitsuyō na mono o yōi suru','Preparo o que é necessário.'],
  ['n3','包む。','tsutsumu','Embrulho.'],
  ['n3','民を治める。','tami o osameru','Governo o povo.'],
  ['n3','令を出す。','rei o dasu','Emito uma ordem.'],
  ['n3','番号を書く。','bangō o kaku','Escrevo o número.'],
  ['n3','飛ぶ鳥がいる。','tobu tori ga iru','Há um pássaro voando.'],
  ['n3','非常に高い。','hijō ni takai','É extremamente alto.'],
  ['n3','無理をしない。','muri o shinai','Não forço.'],
  ['n3','麦を育てる。','mugi o sodateru','Cultivo trigo.'],
  ['n3','変化する。','henka suru','Muda.'],
  ['n3','布を切る。','nuno o kiru','Corto o tecido.'],
  ['n3','判を押す。','han o osu','Carimbo.'],
  ['n3','抱きしめる。','dakishimeru','Abraço.'],
  ['n3','墓参りをする。','hakamairi o suru','Visito o túmulo.'],
  ['n3','模型を作る。','mokei o tsukuru','Faço uma maquete.'],
  ['n3','幕が上がる。','maku ga agaru','A cortina sobe.'],
  ['n3','忘れないようにする。','wasurenai yō ni suru','Faço o possível para não esquecer.'],
  ['n3','望みを持つ。','nozomi o motsu','Tenho esperança.'],
  ['n3','眠る時間がある。','nemuru jikan ga aru','Há tempo para dormir.'],
  ['n3','夢を見る。','yume o miru','Tenho um sonho.'],
  ['n3','要点を言う。','yōten o iu','Digo o ponto principal.'],
  ['n3','養う家族がいる。','yashinau kazoku ga iru','Tenho família para sustentar.'],
  ['n3','領土を守る。','ryōdo o mamoru','Defendo o território.'],
  ['n3','略して言う。','ryaku shite iu','Digo de forma abreviada.'],
  ['n3','臨む。','nozomu','Enfrento.'],
  ['n3','税金を払う。','zeikin o harau','Pago impostos.'],
  ['n3','程度を知る。','teido o shiru','Conheço a medida.'],
  ['n3','突然来る。','totsuzen kuru','Vem de repente.'],
  ['n3','派手な服を着る。','hade na fuku o kiru','Visto roupas chamativas.'],
  ['n3','迫る力がある。','semaru chikara ga aru','Há uma força que se aproxima.'],
  ['n3','抜ける。','nukeru','Saio / Escapa.'],
  ['n3','否定する。','hitei suru','Nego.'],
  ['n3','疲れた体を休める。','tsukareta karada o yasumeru','Descanso o corpo cansado.'],
  ['n3','秘密を守る。','himitsu o mamoru','Guardo o segredo.'],
  ['n3','貧しい生活をする。','mazushii seikatsu o suru','Levo uma vida pobre.'],
  ['n3','府の建物がある。','fu no tatemono ga aru','Há o prédio da prefeitura.'],
  ['n3','富を持つ。','tomi o motsu','Tenho riqueza.'],
  ['n3','怖い話を聞く。','kowai hanashi o kiku','Ouço uma história assustadora.'],
  ['n3','浮かぶ物がある。','ukabu mono ga aru','Há algo que flutua.'],
  ['n3','復元する。','fukugen suru','Recupero / Restauro.'],
  ['n3','腹が立つ。','hara ga tatsu','Fico com raiva.'],
  ['n3','払う。','harau','Pago.'],
  ['n3','兵を集める。','hei o atsumeru','Reúno soldados.'],
  ['n3','辺りを見る。','atari o miru','Olho ao redor.'],
  ['n3','宝を見つける。','takara o mitsukeru','Encontro um tesouro.'],
  ['n3','防ぐ。','fusegu','Previno.'],
  ['n3','娘が育つ。','musume ga sodatsu','A filha cresce.'],
  ['n3','鳴く虫がいる。','naku mushi ga iru','Há insetos que cantam.'],
  ['n3','勇気を持つ。','yūki o motsu','Tenho coragem.'],
  ['n3','雷が鳴る。','kaminari ga naru','O trovão soa.'],
  ['n3','絡まる糸がある。','karamaru ito ga aru','Há fios entrelaçados.'],
  ['n3','乱れた心を整える。','midareta kokoro o totonoeru','Organizo a mente perturbada.'],
  ['n3','陸に上がる。','riku ni agaru','Subo para a terra.'],
  ['n3','絶対に行く。','zettai ni iku','Vou com certeza.'],
  ['n3','看病する。','kanbyō suru','Cuido de um doente.'],
  ['n3','支援する。','shien suru','Apoio.'],
  ['n3','購入する。','kōnyū suru','Compro.'],
  ['n3','輸出する。','yushutsu suru','Exporto.'],
  ['n3','射る。','iru','Flechas / Atiro.'],
  ['n3','戸を開ける。','to o akeru','Abro a porta.'],
  ['n3','城に入る。','shiro ni hairu','Entro no castelo.'],
  ['n3','城に入る。','shiro ni hairu','Entro no castelo.'],
  ['n3','誠実に話す。','seijitsu ni hanasu','Falo com sinceridade.'],
  ['n3','折り紙を作る。','origami o tsukuru','Faço origami.'],
  ['n3','接する。','sessuru','Entro em contato.'],
  ['n3','推理する。','suiri suru','Raciocino.'],
  ['n3','雑誌を読む。','zasshi o yomu','Leio uma revista.'],
  ['n3','参加する。','sanka suru','Participo.'],
  ['n3','嫌いな物がある。','kirai na mono ga aru','Há algo que não gosto.'],
  ['n3','堅い意志を持つ。','katai ishi o motsu','Tenho vontade firme.'],
  ['n3','腰を動かす。','koshi o ugokasu','Mexo a cintura.'],
  ['n3','魂を感じる。','tamashii o kanjiru','Sinto a alma.'],
  ['n3','令を守る。','rei o mamoru','Sigo a ordem.'],
  ['n3','頼る。','tayoru','Confio em.'],
  ['n3','離れる。','hanareru','Me afasto.'],
  ['n3','裏を見る。','ura o miru','Vejo o verso.'],
  ['n3','粒が落ちる。','tsubu ga ochiru','Os grãos caem.'],
  ['n3','恥ずかしい思いをする。','hazukashii omoi o suru','Passo por uma situação embaraçosa.'],
  ['n3','怒る。','okoru','Fico com raiva.'],
  ['n3','情けをかける。','nasake o kakeru','Mostro compaixão.'],
  ['n3','暮らす。','kurasu','Vivo.'],
  ['n3','忙しい日がある。','isogashii hi ga aru','Há dias agitados.'],
  ['n3','与える恩がある。','ataeru on ga aru','Há favores a retribuir.'],
  ['n3','互いに話す。','tagai ni hanasu','Conversamos um com o outro.'],
  ['n3','希望を持つ。','kibō o motsu','Tenho esperança.'],
  ['n3','敬う。','uyamau','Respeito.'],
  ['n3','皆が集まる。','mina ga atsumaru','Todos se reúnem.'],
  ['n3','優しい人がいる。','yasashii hito ga iru','Há uma pessoa gentil.'],
  ['n3','預ける。','azukeru','Deposito / Deixo aos cuidados.'],
  ['n3','迷う。','mayou','Me perco / Hesito.'],
  ['n3','煙が出る。','kemuri ga deru','Sai fumaça.'],
  ['n3','仮の名がある。','kari no na ga aru','Há um nome provisório.'],
  ['n3','暇な時間がある。','hima na jikan ga ару','Tenho tempo livre.'],
  ['n3','貨物を運ぶ。','kamotsu o hakobu','Transporto carga.'],
  ['n3','汗をかく。','ase o kaku','Suo.'],
  ['n3','机の上に本がある。','tsukue no ue ni hon ga aru','Há um livro em cima da mesa.'],
  ['n3','疑問を持つ。','gimon o motsu','Tenho dúvidas.'],
  ['n3','筋が通る。','suji ga tōru','Faz sentido.'],
  ['n3','傾く。','katamuku','Inclina.'],
  ['n3','警告する。','keikoku suru','Aviso.'],
  ['n3','迎える。','mukaeru','Recebo / Vou buscar.'],
  ['n3','激しい雨がある。','hageshii ame ga aru','Há chuva intensa.'],
  ['n3','券を買う。','ken o kau','Compro o bilhete.'],
  ['n3','孔があく。','ana ga aku','Abre um buraco.'],
  ['n3','硬い石がある。','katai ishi ga aru','Há uma pedra dura.'],
  ['n3','香りがいい。','kaori ga ii','O aroma é bom.'],
  ['n3','腹に込める。','hara ni komeru','Guardo dentro de mim.'],
  ['n3','恨みを持つ。','urami o motsu','Guardo rancor.'],
  ['n3','卵を産む。','tamago o umu','Bota um ovo.'],
  ['n3','布を包む。','nuno o tsutsumu','Embrulho o tecido.'],
  ['n3','版を作る。','han o tsukuru','Crio a placa de impressão.'],
  ['n3','墓を守る。','haka o mamoru','Cuido do túmulo.'],
  ['n3','模様を見る。','moyō o miru','Vejo o padrão.'],
  ['n3','忙しく働く。','isogashiku hataraku','Trabalho atarefado.'],
  ['n3','盲目になる。','mōmoku ni naru','Fico cego.'],
  ['n3','夢を追う。','yume o ou','Persigo o sonho.'],
  ['n3','養分を取る。','yōbun o toru','Absorvo nutrientes.'],
  ['n3','律を守る。','ritsu o mamoru','Sigo a lei.'],
  ['n3','輪になる。','wa ni naru','Forma um círculo.'],
  ['n3','罰を受ける。','batsu o ukeru','Recebo uma punição.'],
  ['n3','否か答える。','ika kotaeru','Respondo sim ou não.'],
  ['n3','被害を受ける。','higai o ukeru','Sofro dano.'],
  ['n3','尾を振る。','o o furu','Abana o rabo.'],
  ['n3','符合する。','fugō suru','Coincide.'],
  ['n3','婦人に話す。','fujin ni hanasu','Falo com a senhora.'],
  ['n3','普通の人がいる。','futsū no hito ga iru','Há uma pessoa comum.'],
  ['n3','複雑な問題がある。','fukuzatsu na mondai ga aru','Há um problema complexo.'],
  ['n3','副作用がある。','fukusayō ga aru','Há efeito colateral.'],
  ['n3','幅を広げる。','haba o hirogeru','Amplio o espaço.'],
  ['n3','編む。','amu','Teço.'],
  ['n3','便利な物がある。','benri na mono ga aru','Há uma coisa conveniente.'],
  ['n3','捕まえる。','tsukamaeru','Capturo.'],
  ['n3','補う。','oginau','Complemento.'],
  ['n3','訪問する。','hōmon suru','Visito.'],
  ['n3','牧場で働く。','bokujō de hataraku','Trabalho na fazenda.'],
  ['n3','妙な物がある。','myō na mono ga aru','Há algo estranho.'],
  ['n3','鳴る音がある。','naru oto ga aru','Há um som que ressoa.'],
  ['n3','滅ぶ。','horobiru','Perece.'],
  ['n3','黙って聞く。','damatte kiku','Ouço em silêncio.'],
  ['n3','戻る。','modoru','Volto.'],
  ['n3','誘う。','sasou','Convido.'],
  ['n3','雄大な山がある。','yūdai na yama ga aru','Há uma montanha grandiosa.'],
  ['n3','頼りにする。','tayori ni suru','Confio em.'],
  ['n3','絡む。','karamu','Enrola.'],
  ['n3','陸地に上がる。','rikuchi ni agaru','Subo para o solo.'],
  ['n3','緒につく。','o ni tsuku','Começo.'],
  ['n3','甘い物が好きだ。','amai mono ga suki da','Gosto de coisas doces.'],
  ['n3','巨大な建物がある。','kyodai na tatemono ga aru','Há um edifício enorme.'],
  ['n3','幾つかある。','ikutsu ka aru','Há alguns.'],
  ['n3','系列がある。','keiretsu ga aru','Há uma série.'],
  ['n3','玄関に入る。','genkan ni hairu','Entro na entrada.'],
  ['n3','兼ねる。','kaneru','Acumula funções.'],
  ['n3','更に進む。','sara ni susumu','Avanço ainda mais.'],
  ['n3','克服する。','kokufuku suru','Supero.'],
  ['n3','先を見越す。','saki o mikosu','Antecipo o futuro.'],
  ['n3','販売する。','hanbai suru','Vendo.'],
  ['n3','脚を動かす。','ashi o ugokasu','Mexo a perna.'],
  ['n3','甲子園に行く。','kōshien ni iku','Vou ao Koshien.'],
  ['n3','戸を開ける。','to o akeru','Abro a porta.'],
  ['n3','折る。','oru','Dobro.'],
  ['n3','推理する。','suiri suru','Racionocino.'],
  ['n3','形を見る。','katachi o miru','Vejo a forma.'],
  ['n3','固める。','katameru','Solidificio.'],
  ['n3','限りがある。','kagiri ga aru','Há um limite.'],
  ['n3','押さえる。','osaeru','Pressiono.'],
  ['n3','快晴の日がある。','kaisei no hi ga aru','Há dias de céu limpo.'],
  ['n3','均等に分ける。','kintō ni wakeru','Divido igualmente.'],
  ['n3','禁じる。','kinjiru','Proíbo.'],
  ['n3','師弟関係がある。','shitei kankei ga ару','Há relação mestre-discípulo.'],
  ['n3','似た物がある。','nita mono ga aru','Há algo parecido.'],
  ['n3','軸を中心にする。','jiku o chūshin ni suru','Centralizo no eixo.'],
  ['n3','述べる。','noberu','Declaro.'],
  ['n3','処分する。','shobun suru','Descarto.'],
  ['n3','除く。','nozoku','Removo.'],
  ['n3','晶を見る。','shō o miru','Vejo o cristal.'],
  ['n3','紹介する。','shōkai suru','Apresento.'],
  ['n3','象を見る。','zō o miru','Vejo o elefante.'],
  ['n3','地震が来る。','jishin ga kuru','O terremoto chega.'],
  ['n3','寝る時間だ。','neru jikan da','É hora de dormir.'],
  ['n3','既に知っている。','sude ni shitte iru','Já sei.'],
  ['n3','系統がある。','keitō ga aru','Há um sistema.'],
  ['n3','詠む。','yomu','Declaimo poesia.'],
  ['n3','避ける。','sakeru','Evito.'],
  ['n3','貯める。','tameru','Economizo.'],
  ['n3','援助する。','enjo suru','Auxilio.'],
  ['n3','応じる。','ojiru','Respondo.'],
  ['n3','往来する。','ōrai suru','Transito.'],
  ['n3','仮定する。','katei suru','Suponho.'],
  ['n3','貨物を運ぶ。','kamotsu o hakobu','Transporto carga.'],
  ['n3','改める。','aratameru','Reformulo.'],
  ['n3','灰が残る。','hai ga nokoru','As cinzas ficam.'],
  ['n3','活用する。','katsuyō suru','Utilizo eficientemente.'],
  ['n3','含む。','fukumu','Contenho.'],
  ['n3','奇妙だと思う。','kimyō da to omou','Acho estranho.'],
  ['n3','拒否する。','kyohi suru','Recuso.'],
  ['n3','挙げる。','ageru','Cito / Levanto.'],
  ['n3','供える。','sonaeru','Ofereço.'],
  ['n3','恐れる。','osoreru','Temo.'],
  ['n3','興味がある。','kyōmi ga aru','Tenho interesse.'],
  ['n3','仰ぐ。','aogu','Olho para cima.'],
  ['n3','偶然に会う。','gūzen ni au','Encontro por acaso.'],
  ['n3','刑を受ける。','kei o ukeru','Recebo punição.'],
  ['n3','激しく動く。','hageshiku ugoku','Me movo com intensidade.'],
  ['n3','券売機がある。','kenbaiki ga aru','Há uma máquina de venda.'],
  ['n3','堅く守る。','kataku mamoru','Guardo firmemente.'],
  ['n3','孝行する。','kōkō suru','Demonstro piedade filial.'],
  ['n3','硬い意志がある。','katai ishi ga aru','Há vontade firme.'],
  ['n3','皇室がある。','kōshitsu ga aru','Há uma família imperial.'],
  ['n3','香水をつける。','kōsui o tsukeru','Passo perfume.'],
  ['n3','刻む。','kizamu','Gravo / Entalo.'],
  ['n3','込む。','komu','Fico lotado.'],
  ['n3','恨む。','uramu','Reclamo com rancor.'],
  ['n3','亡くなる。','nakunaru','Falece.'],
  ['n3','包む。','tsutsumu','Embrulho.'],
  ['n3','暮れる。','kureru','Anoitece.'],
  ['n3','泣く子がいる。','naku ko ga iru','Há uma criança chorando.'],
  ['n3','路地を歩く。','roji o aruku','Caminho pelo beco.'],
  ['n3','市場に行く。','ichiba ni iku','Vou ao mercado.'],
  ['n3','増える数がある。','fueru kazu ga aru','Há números que aumentam.'],
  ['n3','値を決める。','ne o kimeru','Determino o preço.'],
  ['n3','吉日がある。','kichijitsu ga aru','Há um dia de bom agouro.'],
  ['n3','一貫する。','ikkan suru','Sou consistente.'],
  ['n3','賀状を送る。','gajō o okuru','Mando um cartão de felicitações.'],
  ['n3','姓名を書く。','seimei o kaku','Escrevo sobrenome e nome.'],
  ['n3','党を作る。','tō o tsukuru','Formo um partido.'],
  ['n3','織物を作る。','orimono o tsukuru','Faço tecido.'],
  ['n3','修理する。','shūri suru','Conserto.'],
  ['n3','折り析く。','ori saku','Dobro e parto.'],
  ['n3','兆しが見える。','kizashi ga mieru','Vejo um sinal.'],
  ['n3','階を上がる。','kai o agaru','Subo um andar.'],
  ['n3','距離がある。','kyori ga aru','Há distância.'],
  ['n3','駆け出す。','kake dasu','Começo a correr.'],
  ['n3','撃つ。','utsu','Atiro.'],
  ['n3','弦を引く。','gen o hiku','Puxo a corda.'],
  ['n3','候補がある。','kōho ga aru','Há candidatos.'],
  ['n3','巧みに動く。','takumi ni ugoku','Me movo habilmente.'],
  ['n3','抗う。','aragau','Resisto.'],
  ['n3','臣が王に話す。','omi ga ō ni hanasu','O ministro fala com o rei.'],
  ['n3','募る。','tsunoru','Intensifica.'],
  ['n3','覧する。','ran suru','Inspeciono.'],
  ['n3','彼が来る。','kare ga kuru','Ele vem.'],
  ['n3','批判する。','hihan suru','Critico.'],
  ['n3','肥える。','koeru','Fica gordo.'],
  ['n3','昌盛する。','shōsei suru','Prospero.'],
  ['n3','召す。','mesu','Chamo.'],
  ['n3','辰年に生まれる。','tatsu-doshi ni umareru','Nasço no ano do dragão.'],
  ['n3','星が光る。','hoshi ga hikaru','A estrela brilha.'],
  ['n3','析出する。','sekishutsu suru','Precipito.'],
  ['n3','昭和の時代がある。','shōwa no jidai ga aru','Há a era Showa.'],
  ['n3','紙を破る。','kami o yaburu','Rasgo o papel.'],
  ['n3','医者は病院で子どもを見る。','isha wa byōin de kodomo o miru','O médico examina as crianças no hospital.'],
  ['n3','兄弟で力を合わせて重い物を持つ。','kyōdai de chikara o awasete omoi mono o motsu','Os irmãos juntam forças e carregam algo pesado.'],
  ['n3','毎日漢字を書いて、言葉の意味を考える。','mainichi kanji o kaite, kotoba no imi o kangaeru','Todo dia escrevo kanji e penso no sentido das palavras.'],
  ['n3','新聞で世界の中の出来事を知る。','shinbun de sekai no naka no dekigoto o shiru','Pelo jornal fico sabendo dos acontecimentos do mundo.'],
  ['n3','強い風が吹いて、木が大きく動く。','tsuyoi kaze ga fuite, ki ga ōkiku ugoku','Um vento forte sopra e a árvore balança bastante.'],
  ['n3','兄は毎朝電車で会社へ通う。','ani wa maiasa densha de kaisha e kayou','Meu irmão mais velho vai de trem à empresa toda manhã.'],
  ['n3','店の主人は客に茶を出す。','mise no shujin wa kyaku ni cha o dasu','O dono da loja serve chá ao cliente.'],
  ['n3','安い肉を買って、家で料理を作る。','yasui niku o katte, ie de ryōri o tsukuru','Compro carne barata e cozinho em casa.'],
  ['n3','地図を見て、駅から海まで歩く。','chizu o mite, eki kara umi made aruku','Olho o mapa e caminho da estação até o mar.'],
  ['n3','王は国を強くするために働く。','ō wa kuni o tsuyoku suru tame ni hataraku','O rei trabalha para tornar o país forte.'],
  /* ── N3 · lote 2 (kanji novos de alta frequência, 2-3 por frase) ── */
  ['n3','昨日から雨が続いて、自宅で休んだ。','kinō kara ame ga tsuzuite, jitaku de yasunda','Desde ontem a chuva continua, então descansei em casa.'],
  ['n3','会議に出席して、長い議論を聞いた。','kaigi ni shusseki shite, nagai giron o kiita','Participei da reunião e ouvi uma longa discussão.'],
  ['n3','好きな番号を選んだら、当たった。','sukina bangō o erandara, atatta','Escolhi o número que eu gosto e acertei.'],
  ['n3','母は妹を何回も店に連れて行く。','haha wa imōto o nankai mo mise ni tsurete iku','Minha mãe leva minha irmã à loja várias vezes.'],
  ['n3','彼は説明が得意だ。','kare wa setsumei ga tokui da','Ele é bom em explicar.'],
  ['n3','実際に見ると、色が違った。','jissai ni miru to, iro ga chigatta','Vendo de verdade, a cor era diferente.'],
  ['n3','右側の道は危ないから、行くのを断った。','migigawa no michi wa abunai kara, iku no o kotowatta','Recusei ir porque o caminho do lado direito é perigoso.'],
  ['n3','弟は二十歳になって、本当に大人になった。','otōto wa hatachi ni natte, hontō ni otona ni natta','Meu irmão fez vinte anos e virou adulto de verdade.'],
  /* ── N2 ── */
  ['n2','着物に彩りのある帯を付ける。','kimono ni irodori no aru obi o tsukeru','Ponho no quimono uma faixa colorida.'],
  ['n2','昔、欧州の帝は強い力を持っていた。','mukashi, ōshū no mikado wa tsuyoi chikara o motte ita','Antigamente, os imperadores da Europa tinham um poder forte.'],
  ['n2','朝、床から起きて、花の露を見た。','asa, toko kara okite, hana no tsuyu o mita','De manhã levantei da cama e vi o orvalho nas flores.'],
  ['n2','廃れた村には人がいない。','sutareta mura ni wa hito ga inai','No vilarejo abandonado não há ninguém.'],
  ['n2','部屋を花で飾って、御飯を作った。','heya o hana de kazatte, gohan o tsukutta','Decorei o quarto com flores e fiz a comida.'],
  ['n2','微かな音で潮が引くのが分かる。','kasukana oto de shio ga hiku no ga wakaru','Pelo som fraquinho dá pra perceber a maré baixando.'],
  ['n2','計画の概要を総合的に説明する。','keikaku no gaiyō o sōgōteki ni setsumei suru','Explico o resumo do plano de forma geral.'],
  ['n2','濃い茶を飲みながら、緩やかな川を見る。','koi cha o nominagara, yuruyakana kawa o miru','Vejo o rio calmo enquanto tomo um chá forte.'],
  ['n2','猛暑の中でも体を鍛える。','mōsho no naka demo karada o kitaeru','Mesmo no calor extremo, treino o corpo.'],
  ['n2','紙に縦の線を引く。','kami ni tate no sen o hiku','Traço uma linha vertical no papel.'],
  ['n2','予算を計算して、計画を縮小した。','yosan o keisan shite, keikaku o shukushō shita','Calculamos o orçamento e reduzimos o plano.'],
  ['n2','難しい問題に鋭い意見を出す。','muzukashii mondai ni surudoi iken o dasu','Dou uma opinião afiada sobre o problema difícil.'],
  ['n2','過去を顧みると懐かしい。','kako o kaerimiru to natsukashii','Olhar pro passado dá saudade.'],
  ['n2','秋の田を巡ると、稲が熟れていた。','aki no ta o meguru to, ine ga urete ita','Percorrendo os campos no outono, o arroz estava maduro.'],
  ['n2','印の付いた紙を工場で刷る。','shirushi no tsuita kami o kōjō de suru','Imprimem na fábrica o papel com a marca.'],
  ['n2','双子は同じ革のかばんを使う。','futago wa onaji kawa no kaban o tsukau','Os gêmeos usam a mesma bolsa de couro.'],
  ['n2','団体の旨を皆に伝える。','dantai no mune o mina ni tsutaeru','Transmito o propósito do grupo a todos.'],
  ['n2','その案は撤回された。','sono an wa tekkai sareta','Aquela proposta foi retirada.'],
  ['n2','先生は基本から学生を導く。','sensei wa kihon kara gakusei o michibiku','O professor guia os alunos a partir da base.'],
  ['n2','彼は独りで絵の展示を見た。','kare wa hitori de e no tenji o mita','Ele viu a exposição de quadros sozinho.'],
  ['n2','風の勢いが強くなる確率は高い。','kaze no ikioi ga tsuyoku naru kakuritsu wa takai','A probabilidade de o vento ficar mais forte é alta.'],
];

const FR_TIERS = [
  ['n5','N5','kanji de base'],
  ['n4','N4','uso cotidiano'],
  ['n3','N3','expressão natural'],
  ['n2','N2','rumo à fluência'],
];

const normFr = s => (s||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'');
const isKanji = ch => /[一-龯]/.test(ch);

function KanjiTok({ ch, selKey, mySel, onSel }){
  const g = window.G(ch);
  const open = selKey === mySel;
  if (!g) return ch;
  return (
    <span
      className={'kj'+(open?' sel':'')}
      onClick={(e)=>{ e.stopPropagation(); onSel(open?null:mySel); }}
    >
      {ch}
      {open && (
        <span className="kj-pop" onClick={e=>e.stopPropagation()}>
          <span className="pk">{ch}<span className="pm">{g.kw}</span></span>
          <span className="prd">
            {g.kun && g.kun!=='—' ? <>kun · {g.kun}<br/></> : null}
            {g.on && g.on!=='—' ? <>on · {g.on}</> : null}
          </span>
          <span className="lk">{g.lvl==='—'?'peça-base':g.lvl}</span>
        </span>
      )}
    </span>
  );
}

function FrCard({ idx, tier, jp, rom, pt, openCard, setOpenCard, showTier }){
  const [sel, setSel] = useFrState(null);
  const open = openCard === idx;
  return (
    <div
      className={'fr-card'+(open?' open':'')}
      onClick={()=>{ setSel(null); setOpenCard(open?null:idx); }}
    >
      {showTier && <span className="fr-tier-badge">{tier.toUpperCase()}</span>}
      <div className="fr-jp">
        {[...jp].map((ch,i)=> isKanji(ch)
          ? <KanjiTok key={i} ch={ch} selKey={sel} mySel={i} onSel={setSel} />
          : <span key={i}>{ch}</span>
        )}
      </div>
      <div className="fr-reveal">
        <div className="fr-rom">{rom}</div>
        <div className="fr-pt">{pt}</div>
      </div>
      <div className="fr-hint"><span className="ar">▸</span> toque para revelar</div>
    </div>
  );
}

function Frases(){
  const [openCard, setOpenCard] = useFrState(null);
  const [search, setSearch] = useFrState('');

  const raw = search.trim();
  const q = normFr(raw);

  const filtered = raw
    ? SENTENCES.filter(([,jp,rom,pt]) =>
        jp.includes(raw) ||
        normFr(rom).includes(q) ||
        normFr(pt).includes(q))
    : null;

  return (
    <div className="fr">
      <div className="fr-intro">
        <h2>Frases</h2>
        <p>Todo kanji aqui já está no seu baralho — só as partículas vêm em kana.
           Toque um <span style={{color:'var(--accent)',fontWeight:700}}>kanji em vermelhão</span> para
           ver o sentido, ou no cartão para revelar a tradução.</p>
        <div className="fr-search">
          <input
            className="fr-sinput"
            type="text"
            value={search}
            onChange={e=>{ setSearch(e.target.value); setOpenCard(null); }}
            placeholder="kanji, romaji ou tradução…"
            autoComplete="off" autoCorrect="off" spellCheck="false"
          />
          {raw && <button className="fr-sclear" onClick={()=>setSearch('')}>×</button>}
        </div>
      </div>

      {filtered ? (
        <div className="fr-sec">
          <div className="sh">
            {filtered.length} frase{filtered.length!==1?'s':''}
            <span style={{textTransform:'none',letterSpacing:0,fontWeight:600,color:'var(--muted)'}}> · {raw}</span>
          </div>
          {filtered.length === 0
            ? <p className="fr-empty">Nenhuma frase encontrada.</p>
            : filtered.map(s=>{
                const idx = SENTENCES.indexOf(s);
                return <FrCard key={idx} idx={idx} tier={s[0]} jp={s[1]} rom={s[2]} pt={s[3]}
                               openCard={openCard} setOpenCard={setOpenCard} showTier />;
              })
          }
        </div>
      ) : (
        FR_TIERS.map(([tier,title,sub])=>(
          <div className="fr-sec" key={tier}>
            <div className="sh">{title} · <span style={{textTransform:'none',letterSpacing:0,fontWeight:600,color:'var(--muted)'}}>{sub}</span></div>
            {SENTENCES.map((s,i)=> s[0]===tier ? (
              <FrCard key={i} idx={i} tier={s[0]} jp={s[1]} rom={s[2]} pt={s[3]}
                      openCard={openCard} setOpenCard={setOpenCard} />
            ) : null)}
          </div>
        ))
      )}
    </div>
  );
}

window.Frases = Frases;
window.SENTENCES = SENTENCES;
