/* ============================================================
   KATAKANA — bônus dentro do Challenge (kana.jsx)
   Não é kanji: array próprio, mesmo formato mínimo que o
   Challenge precisa (id = caractere, kun = leitura romaji).
   46 básicos (gojūon) + dakuten/handakuten.
   ============================================================ */
const KATAKANA = [
  { id:'ア', kun:'a', on:'—', kw:'a', group:'básico' },
  { id:'イ', kun:'i', on:'—', kw:'i', group:'básico' },
  { id:'ウ', kun:'u', on:'—', kw:'u', group:'básico' },
  { id:'エ', kun:'e', on:'—', kw:'e', group:'básico' },
  { id:'オ', kun:'o', on:'—', kw:'o', group:'básico' },
  { id:'カ', kun:'ka', on:'—', kw:'ka', group:'básico' },
  { id:'キ', kun:'ki', on:'—', kw:'ki', group:'básico' },
  { id:'ク', kun:'ku', on:'—', kw:'ku', group:'básico' },
  { id:'ケ', kun:'ke', on:'—', kw:'ke', group:'básico' },
  { id:'コ', kun:'ko', on:'—', kw:'ko', group:'básico' },
  { id:'サ', kun:'sa', on:'—', kw:'sa', group:'básico' },
  { id:'シ', kun:'shi', on:'—', kw:'shi', group:'básico' },
  { id:'ス', kun:'su', on:'—', kw:'su', group:'básico' },
  { id:'セ', kun:'se', on:'—', kw:'se', group:'básico' },
  { id:'ソ', kun:'so', on:'—', kw:'so', group:'básico' },
  { id:'タ', kun:'ta', on:'—', kw:'ta', group:'básico' },
  { id:'チ', kun:'chi', on:'—', kw:'chi', group:'básico' },
  { id:'ツ', kun:'tsu', on:'—', kw:'tsu', group:'básico' },
  { id:'テ', kun:'te', on:'—', kw:'te', group:'básico' },
  { id:'ト', kun:'to', on:'—', kw:'to', group:'básico' },
  { id:'ナ', kun:'na', on:'—', kw:'na', group:'básico' },
  { id:'ニ', kun:'ni', on:'—', kw:'ni', group:'básico' },
  { id:'ヌ', kun:'nu', on:'—', kw:'nu', group:'básico' },
  { id:'ネ', kun:'ne', on:'—', kw:'ne', group:'básico' },
  { id:'ノ', kun:'no', on:'—', kw:'no', group:'básico' },
  { id:'ハ', kun:'ha', on:'—', kw:'ha', group:'básico' },
  { id:'ヒ', kun:'hi', on:'—', kw:'hi', group:'básico' },
  { id:'フ', kun:'fu', on:'—', kw:'fu', group:'básico' },
  { id:'ヘ', kun:'he', on:'—', kw:'he', group:'básico' },
  { id:'ホ', kun:'ho', on:'—', kw:'ho', group:'básico' },
  { id:'マ', kun:'ma', on:'—', kw:'ma', group:'básico' },
  { id:'ミ', kun:'mi', on:'—', kw:'mi', group:'básico' },
  { id:'ム', kun:'mu', on:'—', kw:'mu', group:'básico' },
  { id:'メ', kun:'me', on:'—', kw:'me', group:'básico' },
  { id:'モ', kun:'mo', on:'—', kw:'mo', group:'básico' },
  { id:'ヤ', kun:'ya', on:'—', kw:'ya', group:'básico' },
  { id:'ユ', kun:'yu', on:'—', kw:'yu', group:'básico' },
  { id:'ヨ', kun:'yo', on:'—', kw:'yo', group:'básico' },
  { id:'ラ', kun:'ra', on:'—', kw:'ra', group:'básico' },
  { id:'リ', kun:'ri', on:'—', kw:'ri', group:'básico' },
  { id:'ル', kun:'ru', on:'—', kw:'ru', group:'básico' },
  { id:'レ', kun:'re', on:'—', kw:'re', group:'básico' },
  { id:'ロ', kun:'ro', on:'—', kw:'ro', group:'básico' },
  { id:'ワ', kun:'wa', on:'—', kw:'wa', group:'básico' },
  { id:'ヲ', kun:'wo', on:'—', kw:'wo', group:'básico' },
  { id:'ン', kun:'n', on:'—', kw:'n', group:'básico' },
  { id:'ガ', kun:'ga', on:'—', kw:'ga', group:'dakuten' },
  { id:'ギ', kun:'gi', on:'—', kw:'gi', group:'dakuten' },
  { id:'グ', kun:'gu', on:'—', kw:'gu', group:'dakuten' },
  { id:'ゲ', kun:'ge', on:'—', kw:'ge', group:'dakuten' },
  { id:'ゴ', kun:'go', on:'—', kw:'go', group:'dakuten' },
  { id:'ザ', kun:'za', on:'—', kw:'za', group:'dakuten' },
  { id:'ジ', kun:'ji', on:'—', kw:'ji', group:'dakuten' },
  { id:'ズ', kun:'zu', on:'—', kw:'zu', group:'dakuten' },
  { id:'ゼ', kun:'ze', on:'—', kw:'ze', group:'dakuten' },
  { id:'ゾ', kun:'zo', on:'—', kw:'zo', group:'dakuten' },
  { id:'ダ', kun:'da', on:'—', kw:'da', group:'dakuten' },
  { id:'ヂ', kun:'dji', on:'—', kw:'dji', group:'dakuten' },
  { id:'ヅ', kun:'dzu', on:'—', kw:'dzu', group:'dakuten' },
  { id:'デ', kun:'de', on:'—', kw:'de', group:'dakuten' },
  { id:'ド', kun:'do', on:'—', kw:'do', group:'dakuten' },
  { id:'バ', kun:'ba', on:'—', kw:'ba', group:'dakuten' },
  { id:'ビ', kun:'bi', on:'—', kw:'bi', group:'dakuten' },
  { id:'ブ', kun:'bu', on:'—', kw:'bu', group:'dakuten' },
  { id:'ベ', kun:'be', on:'—', kw:'be', group:'dakuten' },
  { id:'ボ', kun:'bo', on:'—', kw:'bo', group:'dakuten' },
  { id:'パ', kun:'pa', on:'—', kw:'pa', group:'handakuten' },
  { id:'ピ', kun:'pi', on:'—', kw:'pi', group:'handakuten' },
  { id:'プ', kun:'pu', on:'—', kw:'pu', group:'handakuten' },
  { id:'ペ', kun:'pe', on:'—', kw:'pe', group:'handakuten' },
  { id:'ポ', kun:'po', on:'—', kw:'po', group:'handakuten' },
];
window.KATAKANA = KATAKANA;
